coverage:
  precision: 0
  round: down
  notify:
    require_ci_to_pass: yes
  status:
    patch:
      default:
        target: '90'
    project:
      default:
        target: auto
        threshold: 1%
