codecov:
  token: 22038cfb-2cde-4b1b-ba9e-263c1cb6d561
coverage:
  precision: 0
  round: down
  status:
    patch:
      default:
        target: 97
    project:
      default:
        threshold: 1%
comment: false
