version: 2
formats:
    - htmlzip
    - pdf
build:
    image: testing
python:
    version: 3.9
    install:
        - method: pip
          path: .
          extra_requirements:
              - docs
sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: true
