.TH isympy 1 "March 21, 2007"  
.SH NAME
sympy \- interactive console for SymPy (Symbolic Python)
.SH SYNOPSIS
\fBsympy\fR [\fB\-e this\fR] [\fB\-\-example that\fR]
.SH ISYMPY
This manual page documents briefly the
sympy command.
.PP
isympy is a Python shell for SymPy. It imports the modules
sympy and defines the symbols x, y, z. 
.SH OPTIONS
These programs follow the usual GNU command line syntax,
with long options starting with two dashes (`\-'). A summary of
options is included below. For a complete description, see the
Info files.
.TP 
\fB\-h\fR 
Show summary of options.
.TP 
\fB\-c\fR 
specify a python interactive interpreter, 
currently only python or ipython. Example usage: 
\&./shell.py \-c python
.SH "SEE ALSO"
.SH AUTHOR
This manual page was written by Fabian fabian@fseoane.net. Sympy 
is written by Ondrej Certik and Fabian
.PP
On Debian systems, the complete text of the GNU General Public
License can be found in /usr/share/common\-licenses/GPL.
