"""
The contents of this file are the return value of
``sympy.assumptions.ask.compute_known_facts``.  Do NOT manually
edit this file.  Instead, run ./bin/ask_update.py.
"""

from sympy.logic.boolalg import And, Not, Or
from sympy.assumptions.ask import Q

# -{ Known facts in CNF }-
known_facts_cnf = And(
    Or(Q.invertible, Q.singular),
    Or(Q.nonzero, Q.zero),
    Or(Not(Q.rational), Q.algebraic),
    Or(Not(Q.imaginary), Q.antihermitian),
    Or(Not(Q.algebraic), Q.complex),
    Or(Not(Q.imaginary), Q.complex),
    Or(Not(Q.real), Q.complex),
    Or(Not(Q.transcendental), Q.complex),
    Or(Not(Q.real_elements), Q.complex_elements),
    Or(Not(Q.zero), Q.even),
    Or(Not(Q.negative), Q.extended_real),
    Or(Not(Q.nonnegative), Q.extended_real),
    Or(Not(Q.nonpositive), Q.extended_real),
    Or(Not(Q.positive), Q.extended_real),
    Or(Not(Q.real), Q.extended_real),
    Or(Not(Q.zero), Q.extended_real),
    Or(Not(Q.complex), Q.finite),
    Or(Not(Q.real), Q.finite),
    Or(Not(Q.zero), Q.finite),
    Or(Not(Q.invertible), Q.fullrank),
    Or(Not(Q.real), Q.hermitian),
    Or(Not(Q.even), Q.integer),
    Or(Not(Q.odd), Q.integer),
    Or(Not(Q.prime), Q.integer),
    Or(Not(Q.positive_definite), Q.invertible),
    Or(Not(Q.unitary), Q.invertible),
    Or(Not(Q.diagonal), Q.lower_triangular),
    Or(Not(Q.positive), Q.nonnegative),
    Or(Not(Q.zero), Q.nonnegative),
    Or(Not(Q.negative), Q.nonpositive),
    Or(Not(Q.zero), Q.nonpositive),
    Or(Not(Q.negative), Q.nonzero),
    Or(Not(Q.positive), Q.nonzero),
    Or(Not(Q.diagonal), Q.normal),
    Or(Not(Q.unitary), Q.normal),
    Or(Not(Q.prime), Q.positive),
    Or(Not(Q.orthogonal), Q.positive_definite),
    Or(Not(Q.integer), Q.rational),
    Or(Not(Q.irrational), Q.real),
    Or(Not(Q.noninteger), Q.real),
    Or(Not(Q.rational), Q.real),
    Or(Not(Q.integer_elements), Q.real_elements),
    Or(Not(Q.invertible), Q.square),
    Or(Not(Q.normal), Q.square),
    Or(Not(Q.symmetric), Q.square),
    Or(Not(Q.diagonal), Q.symmetric),
    Or(Not(Q.lower_triangular), Q.triangular),
    Or(Not(Q.unit_triangular), Q.triangular),
    Or(Not(Q.upper_triangular), Q.triangular),
    Or(Not(Q.orthogonal), Q.unitary),
    Or(Not(Q.diagonal), Q.upper_triangular),
    Or(Not(Q.algebraic), Not(Q.transcendental)),
    Or(Not(Q.composite), Not(Q.prime)),
    Or(Not(Q.even), Not(Q.odd)),
    Or(Not(Q.finite), Not(Q.infinite)),
    Or(Not(Q.integer), Not(Q.noninteger)),
    Or(Not(Q.invertible), Not(Q.singular)),
    Or(Not(Q.irrational), Not(Q.rational)),
    Or(Not(Q.negative), Not(Q.nonnegative)),
    Or(Not(Q.nonpositive), Not(Q.positive)),
    Or(Not(Q.nonzero), Not(Q.zero)),
    Or(Not(Q.complex), Q.algebraic, Q.transcendental),
    Or(Not(Q.integer), Q.even, Q.odd),
    Or(Not(Q.real), Q.integer, Q.noninteger),
    Or(Not(Q.real), Q.irrational, Q.rational),
    Or(Not(Q.triangular), Q.lower_triangular, Q.upper_triangular),
    Or(Not(Q.extended_real), Q.negative, Q.nonnegative),
    Or(Not(Q.extended_real), Q.nonpositive, Q.positive),
    Or(Not(Q.lower_triangular), Not(Q.upper_triangular), Q.diagonal),
    Or(Not(Q.fullrank), Not(Q.square), Q.invertible),
    Or(Not(Q.nonpositive), Not(Q.nonzero), Q.negative),
    Or(Not(Q.real), Not(Q.unitary), Q.orthogonal),
    Or(Not(Q.nonnegative), Not(Q.nonzero), Q.positive),
    Or(Not(Q.extended_real), Not(Q.finite), Q.real),
    Or(Not(Q.antihermitian), Not(Q.hermitian), Q.zero),
    Or(Not(Q.imaginary), Not(Q.real), Q.zero),
    Or(Not(Q.nonnegative), Not(Q.nonpositive), Q.zero),
    Or(Not(Q.extended_real), Q.negative, Q.positive, Q.zero),
    Or(Not(Q.integer), Not(Q.positive), Q.composite, Q.prime)
)

# -{ Known facts in compressed sets }-
known_facts_dict = {
    Q.algebraic: {Q.algebraic, Q.complex, Q.finite},
    Q.antihermitian: {Q.antihermitian},
    Q.commutative: {Q.commutative},
    Q.complex: {Q.complex, Q.finite},
    Q.complex_elements: {Q.complex_elements},
    Q.composite: {Q.composite},
    Q.diagonal: {Q.diagonal, Q.lower_triangular, Q.normal, Q.square,
        Q.symmetric, Q.triangular, Q.upper_triangular},
    Q.even: {Q.algebraic, Q.complex, Q.even, Q.extended_real, Q.finite,
        Q.hermitian, Q.integer, Q.rational, Q.real},
    Q.extended_real: {Q.extended_real},
    Q.finite: {Q.finite},
    Q.fullrank: {Q.fullrank},
    Q.hermitian: {Q.hermitian},
    Q.imaginary: {Q.antihermitian, Q.complex, Q.finite, Q.imaginary},
    Q.infinite: {Q.infinite, Q.nonzero},
    Q.infinitesimal: {Q.infinitesimal},
    Q.integer: {Q.algebraic, Q.complex, Q.extended_real, Q.finite,
        Q.hermitian, Q.integer, Q.rational, Q.real},
    Q.integer_elements: {Q.complex_elements, Q.integer_elements,
        Q.real_elements},
    Q.invertible: {Q.fullrank, Q.invertible, Q.square},
    Q.irrational: {Q.complex, Q.extended_real, Q.finite, Q.hermitian,
        Q.irrational, Q.noninteger, Q.nonzero, Q.real},
    Q.is_true: {Q.is_true},
    Q.lower_triangular: {Q.lower_triangular, Q.triangular},
    Q.negative: {Q.extended_real, Q.negative, Q.nonpositive, Q.nonzero},
    Q.noninteger: {Q.complex, Q.extended_real, Q.finite, Q.hermitian,
        Q.noninteger, Q.nonzero, Q.real},
    Q.nonnegative: {Q.extended_real, Q.nonnegative},
    Q.nonpositive: {Q.extended_real, Q.nonpositive},
    Q.nonzero: {Q.nonzero},
    Q.normal: {Q.normal, Q.square},
    Q.odd: {Q.algebraic, Q.complex, Q.extended_real, Q.finite,
        Q.hermitian, Q.integer, Q.nonzero, Q.odd, Q.rational, Q.real},
    Q.orthogonal: {Q.fullrank, Q.invertible, Q.normal, Q.orthogonal,
        Q.positive_definite, Q.square, Q.unitary},
    Q.positive: {Q.extended_real, Q.nonnegative, Q.nonzero, Q.positive},
    Q.positive_definite: {Q.fullrank, Q.invertible, Q.positive_definite,
        Q.square},
    Q.prime: {Q.algebraic, Q.complex, Q.extended_real, Q.finite,
        Q.hermitian, Q.integer, Q.nonnegative, Q.nonzero, Q.positive,
        Q.prime, Q.rational, Q.real},
    Q.rational: {Q.algebraic, Q.complex, Q.extended_real, Q.finite,
        Q.hermitian, Q.rational, Q.real},
    Q.real: {Q.complex, Q.extended_real, Q.finite, Q.hermitian, Q.real},
    Q.real_elements: {Q.complex_elements, Q.real_elements},
    Q.singular: {Q.singular},
    Q.square: {Q.square},
    Q.symmetric: {Q.square, Q.symmetric},
    Q.transcendental: {Q.complex, Q.finite, Q.nonzero, Q.transcendental},
    Q.triangular: {Q.triangular},
    Q.unit_triangular: {Q.triangular, Q.unit_triangular},
    Q.unitary: {Q.fullrank, Q.invertible, Q.normal, Q.square, Q.unitary},
    Q.upper_triangular: {Q.triangular, Q.upper_triangular},
    Q.zero: {Q.algebraic, Q.complex, Q.even, Q.extended_real, Q.finite,
        Q.hermitian, Q.integer, Q.nonnegative, Q.nonpositive,
        Q.rational, Q.real, Q.zero},
}
